export interface Complain {
    name: string,
    phoneNumber: string,
    email: string,
    state: string,
    district: string,
    pinCode: number,
    address: string,
    productName: string,
    product: string,
    modalNumber: string,
    serialNumber: string,
    description: string,
    complainDate: string,
}